# Generated by Django 4.1.1 on 2022-09-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Emp',
        ),
    ]
