# Generated by Django 4.1.1 on 2022-09-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_emp_emp_id_alter_emp_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='phone',
        ),
    ]
