# Generated by Django 4.1.1 on 2022-09-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_remove_emp_emp_id_remove_emp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
