# Generated by Django 4.1.1 on 2022-09-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_emp_emp_id_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
