# Generated by Django 4.1.1 on 2022-09-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_remove_emp_address_remove_emp_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='address',
            field=models.CharField(default='Address Pune', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='department',
            field=models.CharField(default='Address Pune', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emp',
            name='name',
            field=models.CharField(default='Mujahid', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='phone_no',
            field=models.IntegerField(default=9507008142),
        ),
        migrations.AddField(
            model_name='emp',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
